name: flutter_taiwan_zip
description: Dropdown menu for querying zip codes in Taiwan.
version: 0.2.0
publish_to: none

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  bloc: ^8.0.2
  bloc_test: ^9.0.2
  equatable: ^2.0.3
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  taiwan_zip: ^0.2.0

dev_dependencies:
  flutter_lints: ^1.0.4
  flutter_test:
    sdk: flutter
  
flutter:
  uses-material-design: true