name: flutter_taiwan_zip
description: Dropdown menu for querying zip codes in Taiwan.
version: 0.5.1
publish_to: none

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  bloc: ^8.0.2
  bloc_test: ^9.0.2
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  freezed_annotation: ^1.1.0
  taiwan_zip: ^0.3.0

dev_dependencies:
  build_runner: ^2.1.7
  flutter_lints: ^1.0.4
  flutter_test:
    sdk: flutter
  freezed: ^1.1.0
  
flutter:
  uses-material-design: true