name: flutter_taiwan_zip
description: Dropdown menu for zip code
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  bloc: ^8.0.2
  bloc_test: ^9.0.2
  build_runner: ^2.1.7
  equatable: ^2.0.3
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  json_annotation: ^4.4.0

  taiwan_zip:
    path: packages/taiwan_zip

dev_dependencies:
  flutter_lints: ^1.0.4
  flutter_test:
    sdk: flutter
  json_serializable: ^6.1.4
  
flutter:
  uses-material-design: true